"""
Specifiers of the image object-detection components.
"""
from ._UFDLImageObjectDetectionSourceStageSpecifier import UFDLImageObjectDetectionSourceStageSpecifier
from ._UFDLImageObjectDetectionSinkStageSpecifier import UFDLImageObjectDetectionSinkStageSpecifier
