from ._UFDLClassifyInputFormatSpecifier import UFDLClassifyInputFormatSpecifier
from ._UFDLObjDetInputFormatSpecifier import UFDLObjDetInputFormatSpecifier
from ._UFDLObjDetOutputFormatSpecifier import UFDLObjDetOutputFormatSpecifier
