"""
Specifiers of the spectrum classification components.
"""
from ._UFDLSpectrumClassificationSinkStageSpecifier import UFDLSpectrumClassificationSinkStageSpecifier
from ._UFDLSpectrumClassificationSourceStageSpecifier import UFDLSpectrumClassificationSourceStageSpecifier
